version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
